import mongoose, { Schema, Document } from 'mongoose';

export interface ITransaction extends Document {
  txnId: string; // The UUID generated by the POS (ensures idempotency)
  cardId: mongoose.Types.ObjectId;
  retailerId: string;
  volume: number;
  status: 'Approved' | 'Denied' | 'Pending' | 'Synced' | 'Rejected';
  source: 'Online' | 'Offline';
  timestamp: Date;
}

const TransactionSchema: Schema = new Schema({
  txnId: { type: String, required: true, unique: true }, // unique index for idempotency
  cardId: { type: Schema.Types.ObjectId, ref: 'Card', required: true },
  retailerId: { type: String, required: true },
  volume: { type: Number, required: true },
  status: { type: String, enum: ['Approved', 'Denied', 'Pending', 'Synced', 'Rejected'], required: true },
  source: { type: String, enum: ['Online', 'Offline'], required: true },
  timestamp: { type: Date, required: true },
}, { timestamps: true });

export default mongoose.model<ITransaction>('Transaction', TransactionSchema);
